FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY endpoint.web/. ./web/

WORKDIR /app/web

RUN dotnet restore -r linux-x64
RUN dotnet publish -c Release -o out -r linux-x64 --self-contained false --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app
COPY --from=build /app/web/out ./

ENTRYPOINT ["./endpoint.web"]

