global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "dotnet"
    static_configs:
      - targets: ["192.168.1.3:5000"]

  - job_name: "node"
    static_configs:
      - targets: ["192.168.1.1:9100", "192.168.1.3:9100", "192.168.1.12:9100", "192.168.1.7:9182"]

  - job_name: "speedtest"
    scrape_interval: 1h
    scrape_timeout: 1m
    static_configs:
      - targets: ["192.168.1.1:9798"]
